name: NodeJS Build Process

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm t

    # - name: Upload test-results-${{ matrix.node-version }}
    #   uses: actions/upload-artifact@v4
    #   if: success() || failure()
    #   with:
    #     name: test-results-${{ matrix.node-version }}
    #     path: test-results.xml

    - name: Coverage
      run: npm run test:coverage

    # - name: Upload coverage-results-${{ matrix.node-version }}
    #   uses: actions/upload-artifact@v4
    #   if: success() || failure()
    #   with:
    #     name: coverage-results-${{ matrix.node-version }}
    #     path: ./coverage/lcov.info

    - name: Mutation Test
      run: npm run test:mutation

    # - name: Upload mutation-results-${{ matrix.node-version }}
    #   uses: actions/upload-artifact@v4
    #   if: success() || failure()
    #   with:
    #     name: mutation-results-${{ matrix.node-version }}
    #     path: ./reports/mutation/mutation.json
